version: "3.7"
services:
  db:
    image: postgres:13.4-alpine
    # container_name: rails_7_with_docker_db_1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: my_app
      # DATABASE_URL: postgres://postgres:postgres@db:5432/my_app
      environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  demo-web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      # POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app  
      DATABASE_URL: postgres://postgres:postgres@db:5432/my_app  # Database connection parameters
      # volumes: 
        # - "app-storage:/rails/storage"
    ports: 
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
  app-storage: {}
networks: 
  demo_default:




